parsers:
  - format: json
    className: com.example.dataflow.generic.parser.impl.JsonMessageParser
    config: {}
  - format: csv
    className: com.example.dataflow.generic.parser.impl.CsvMessageParser
    config:
      delimiter: ","
      hasHeader: false
      columns:
        - id
        - name
        - amount
  - format: xml
    className: com.example.dataflow.generic.parser.impl.XmlMessageParser
    config: {}
  - format: avro
    className: com.example.dataflow.generic.parser.impl.AvroMessageParser
    config:
      topic: "teamA-input"
      schemaRegistryUrl: "https://<confluent-schema-registry-endpoint>"
      basicAuthCredentialsSource: "USER_INFO"
      schemaRegistryBasicAuthUserInfo: "<sr-api-key>:<sr-api-secret>"
  - format: protobuf
    className: com.example.dataflow.generic.parser.impl.ProtobufMessageParser
    config:
      topic: "teamA-input"
      schemaRegistryUrl: "https://<confluent-schema-registry-endpoint>"
      basicAuthCredentialsSource: "USER_INFO"
      schemaRegistryBasicAuthUserInfo: "<sr-api-key>:<sr-api-secret>"
  - format: raw
    className: com.example.dataflow.generic.parser.impl.RawStringMessageParser
    config: {}
